functionsDirectory = "C:\\Users\\Huawei\\CascadeProjects\\electronic-service-tech\\netlify\\functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\Huawei\\CascadeProjects\\electronic-service-tech"
publishOrigin = "config"
commandOrigin = "config"
command = "echo Static site ready"
functions = "C:\\Users\\Huawei\\CascadeProjects\\electronic-service-tech\\netlify\\functions"

[build.environment]

[build.processing]
ignore_html_forms = false

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]